from __future__ import annotations

import shlex
from collections.abc import Sequence

from redot_compat.models import CompatibilityResult, CompatibilityStatus

_MANIFEST_PLACEHOLDER = "__REDOT_COMPAT_MANIFEST__"


def render_powershell_reproduction(result: CompatibilityResult) -> str:
    command = _command(result)
    arguments = ",\n    ".join(_powershell_argument(item) for item in command[1:])
    expected_exit = _expected_exit(result.classification)
    expected_hash = result.source.archive_sha256
    return f"""# Generated by redot-compat {result.tester_version}.
param([string]$Output = (Join-Path (Get-Location) 'redot-compat-reproduced'))
$ErrorActionPreference = 'Stop'
$Arguments = @(
    {arguments}
)
& {_powershell_quote(command[0])} @Arguments --output $Output
$Code = $LASTEXITCODE
if ($Code -ne {expected_exit}) {{ throw "Unexpected redot-compat exit code: $Code" }}
$Payload = Get-Content -LiteralPath (Join-Path $Output 'result.json') -Raw | ConvertFrom-Json
$Expected = '{expected_hash}'
if ($Payload.source.archive_sha256 -ne $Expected) {{
    throw "Source hash mismatch: $($Payload.source.archive_sha256)"
}}
Write-Output "Reproduced $($Payload.classification) with source SHA-256 $Expected"
"""


def render_bash_reproduction(result: CompatibilityResult) -> str:
    command = _command(result)
    rendered = " \\\n  ".join(_bash_argument(item) for item in command)
    expected_exit = _expected_exit(result.classification)
    expected_hash = result.source.archive_sha256
    hash_reader = (
        "import json,sys; "
        'print(json.load(open(sys.argv[1], encoding="utf-8"))'
        '["source"]["archive_sha256"])'
    )
    return f"""#!/usr/bin/env bash
# Generated by redot-compat {result.tester_version}.
set -u -o pipefail
script_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
output="${{1:-$PWD/redot-compat-reproduced}}"
set +e
{rendered} \\
  --output "$output"
code=$?
set -e
if [ "$code" -ne {expected_exit} ]; then
  echo "Unexpected redot-compat exit code: $code" >&2
  exit 1
fi
hash_reader={shlex.quote(hash_reader)}
actual="$(python -c "$hash_reader" "$output/result.json")"
expected={shlex.quote(expected_hash)}
if [ "$actual" != "$expected" ]; then
  echo "Source hash mismatch: $actual" >&2
  exit 1
fi
echo "Reproduced source SHA-256 $expected"
"""


def _command(result: CompatibilityResult) -> list[str]:
    value = result.reproduction.get("command")
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes)):
        command = [str(item) for item in value]
        if command:
            return command
    command = ["redot-compat", "inspect", result.source.requested_url_or_path]
    if result.source.resolved_commit:
        command.extend(["--ref", result.source.resolved_commit])
    elif result.source.release_tag:
        command.extend(["--release", result.source.release_tag])
        if result.source.release_asset_name:
            command.extend(["--asset", result.source.release_asset_name])
    return command


def _powershell_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _powershell_argument(value: str) -> str:
    if value == _MANIFEST_PLACEHOLDER:
        return "(Join-Path $PSScriptRoot 'reproduce-manifest.json')"
    return _powershell_quote(value)


def _bash_argument(value: str) -> str:
    if value == _MANIFEST_PLACEHOLDER:
        return '"$script_dir/reproduce-manifest.json"'
    return shlex.quote(value)


def _expected_exit(status: CompatibilityStatus) -> int:
    if status in {
        CompatibilityStatus.COMPATIBLE_UNCHANGED,
        CompatibilityStatus.COMPATIBLE_REPACKAGE_ONLY,
    }:
        return 0
    if status is CompatibilityStatus.NO_PORT_NEEDED_BASELINE_POLICY:
        return 10
    if status.value.startswith("PORT_REQUIRED_") or status is CompatibilityStatus.ENGINE_API_GAP:
        return 20
    if status in {
        CompatibilityStatus.INVALID_PACKAGE,
        CompatibilityStatus.UPSTREAM_PACKAGE_FAILURE,
    }:
        return 30
    if status is CompatibilityStatus.INTERNAL_TESTER_ERROR:
        return 50
    return 40
